/**
 * Pesaway Pesamoni API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pesamoni


case class InlineResponse200 (
  status: Option[String] = None,
  token: Option[String] = None,
  description: Option[String] = None,
  mobile: Option[String] = None,
  statuscode: Option[String] = None,
  transactionType: Option[String] = None
)

